# Generated by Django 5.2.9 on 2026-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('uploaded_id', models.FileField(upload_to='campers_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
