# Generated by Django 5.2.9 on 2026-01-13 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camperregister',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campparticipant',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.camp'),
        ),
        migrations.AddField(
            model_name='campparticipant',
            name='camper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='main.camperregister'),
        ),
        migrations.AlterUniqueTogether(
            name='campparticipant',
            unique_together={('camper', 'camp')},
        ),
    ]
