# Generated by Django 5.2.9 on 2026-01-10 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='camper',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='camper',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campers', to=settings.AUTH_USER_MODEL),
        ),
    ]
