# Generated by Django 5.2.9 on 2026-01-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_camper_parent_name_remove_camper_parent_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название лагеря')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало смены')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец смены')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Максимум детей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CamperRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО ребёнка')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('uploaded_id', models.FileField(upload_to='campers_ids/', verbose_name='PDF удостоверения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='main.camp')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(verbose_name='Дата начала смены')),
                ('end_date', models.DateField(verbose_name='Дата окончания смены')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.camp')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='main.camperregister')),
            ],
            options={
                'verbose_name': 'Участник лагеря',
                'verbose_name_plural': 'Участники лагеря',
                'unique_together': {('camper', 'camp')},
            },
        ),
        migrations.DeleteModel(
            name='Camper',
        ),
    ]
