# Generated by Django 5.2.9 on 2026-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_camp_camperregister_campparticipant_delete_camper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
